apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-dotnet-basic-fiyxqkdk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-dotnet-basic-fiyxqkdk 
  name: backend-tests-dotnet-basic-fiyxqkdk
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-dotnet-basic-fiyxqkdk 
